FROM rust:1.71.1-slim-bookworm as builder

WORKDIR /usr/src/yangtze
COPY . .
RUN apt-get update && apt-get install -y protobuf-compiler
RUN cargo install --path ./apiserver

FROM ubuntu:22.04
COPY --from=builder /usr/local/cargo/bin/flame-executor-manager /opt/yangtze-apiserver

ENTRYPOINT ["/opt/yangtze-apiserver"]