FROM rust:1.71.1-slim-bookworm as builder

WORKDIR /usr/src/yangtze
COPY . .
RUN apt-get update && apt-get install -y protobuf-compiler
RUN cargo install --path ./yzctl

FROM ubuntu:22.04
RUN apt-get update && apt-get install -y wget vim iputils-ping ssh
COPY --from=builder /usr/local/cargo/bin/yzctl /usr/local/bin/yzctl

CMD ["service", "ssh", "start", "-D"]